name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14' ]
        redis: [ '3', '4', '5', '6' ]
    name: Node ${{ matrix.node }} Redis ${{ matrix.redis }}
    steps:
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis }}
          number of databases: 1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test
        run: yarn run test
