name: CI
on: [push, workflow_dispatch, pull_request_target]
jobs:
  build:
    strategy:
      matrix:
        node: [ '14', '16', '18']
        redis: [ '3', '4', '5', '6' ]
        mysql: [ '5.6', '5.7', '8' ]
        os: ['ubuntu-latest']
    runs-on: ${{ matrix.os }}
    name: Node ${{ matrix.node }} Redis ${{ matrix.redis }} Mysql ${{ matrix.mysql }} OS ${{ matrix.os }}
    steps:
      - name: Setup Redis
        uses: zhulik/redis-action@1.1.0
        with:
          redis version: ${{ matrix.redis }}
          number of databases: 1
      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql database: 'queue'
          mysql root password: 'root'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: yarn
        run: yarn
      - name: yarn run test
        run: yarn run test
